import React from "react";

const Footer = () => {
  return (
    <div className="w-full border-t border-gray-300 pt-1 mt-1 flex flex-row justify-between">
      <p className="text-xs text-gray-500">
        Printed on: {new Date().toLocaleString()}
      </p>
      <div className="text-xs text-gray-500">
        This report generated by DardiBook software
      </div>
    </div>
  );
};

export default Footer;
