import React from "react";

const BillReceiptPrint = ({ data }: { data: BillData }) => {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm">
        <div>
          <span className="font-medium">Patient ID:</span> {data.patient_id}
        </div>
        <div>
          <span className="font-medium">Patient Name:</span> {data.name}
        </div>
        <div>
          <span className="font-medium">Patient Contact:</span> {data.mobile}
        </div>
        <div>
          <span className="font-medium">Patient Gender:</span> {data.gender}
        </div>
        <div>
          <span className="font-medium">Bill Number:</span> {data.bill_id}
        </div>
        <div>
          <span className="font-medium">Prescription ID:</span>{" "}
          {data.prescription_id}
        </div>
        <div>
          <span className="font-medium">Bill Date:</span>{" "}
          {new Date(data.generated_at).toLocaleString("en-GB")}
        </div>
        <div>
          <span className="font-medium">Prescribed By:</span>{" "}
          {data.prescribed_by}
        </div>
        <div>
          <span className="font-medium">Generated By:</span> {data.generated_by}
        </div>
        <div>
          <span className="font-medium">Payment Status:</span>{" "}
          {data.payment_status}
        </div>
        {data.payment_status === "Paid" && (
          <div>
            <span className="font-medium">Payment Method:</span>{" "}
            {data.payment_method}
          </div>
        )}
      </div>

      {data.medicines.length > 0 && (
        <div>
          <table className="w-full text-sm border-collapse border border-gray-300">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 p-2 text-left">
                  Medication
                </th>
                <th className="border border-gray-300 p-2 text-left">
                  Instruction
                </th>
                <th className="border border-gray-300 p-2 text-left">Dosage</th>
                <th className="border border-gray-300 p-2 text-left">
                  Duration
                </th>

                <th className="border border-gray-300 p-2 text-left">
                  Quantity
                </th>
                <th className="border border-gray-300 p-2 text-left">
                  Price(₹)
                </th>
                <th className="border border-gray-300 p-2 text-left">
                  Total(₹)
                </th>
              </tr>
            </thead>
            <tbody>
              {data.medicines.map((med, index) => (
                <tr key={index}>
                  <td className="border border-gray-300 p-2">
                    {med.medicineName} ({med.type})
                  </td>
                  <td className="border border-gray-300 p-2">
                    {med.instruction}
                  </td>
                  <td className="border border-gray-300 p-2">
                    {med.dosages.morning} - {med.dosages.afternoon} -{" "}
                    {med.dosages.evening} - {med.dosages.night}
                  </td>
                  <td className="border border-gray-300 p-2">
                    {med.duration} {med.durationType}
                  </td>
                  <td className="border border-gray-300 p-2">{med.quantity}</td>
                  <td className="border border-gray-300 p-2">{med.price}</td>
                  <td className="border border-gray-300 p-2">
                    {med.quantity * med.price}
                  </td>
                </tr>
              ))}
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td className="border border-gray-300 p-2 font-medium text-right">
                  Total :
                </td>
                <td className="border border-gray-300 p-2">
                  {data.medicines.reduce(
                    (sum, item) => sum + item.price * item.quantity,
                    0
                  )}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      )}

      {data.services.length > 0 && (
        <div>
          <table className="w-full text-sm border-collapse border border-gray-300">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 p-2 text-left">
                  Service
                </th>
                <th className="border border-gray-300 p-2 text-left">
                  Quantity
                </th>
                <th className="border border-gray-300 p-2 text-left">
                  Price(₹)
                </th>
              </tr>
            </thead>
            <tbody>
              {data.services.map((service, index) => (
                <tr key={index}>
                  <td className="border border-gray-300 p-2">
                    {service.service_name}
                  </td>
                  <td className="border border-gray-300 p-2">
                    {service.quantity}
                  </td>
                  <td className="border border-gray-300 p-2">
                    {service.price}
                  </td>
                </tr>
              ))}
              <tr>
                <td></td>
                <td className="border border-gray-300 p-2 font-medium text-right">
                  Total :
                </td>
                <td className="border border-gray-300 p-2">
                  {data.services.reduce((sum, item) => sum + item.price, 0)}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      )}

      <div className="flex justify-end">
        <div className="w-1/2 text-sm">
          <div className="flex justify-between py-1 border-b">
            <span>Discount:</span>
            <span>{data.discount.toFixed(2)}%</span>
          </div>

          <div className="flex justify-between py-1 border-b">
            <span>Tax:</span>
            <span>{data.tax_percentage.toFixed(2)}%</span>
          </div>

          <div className="flex justify-between py-1 border-b">
            <span>Total Amount:</span>
            <span>₹{data.total_amount.toFixed(2)}</span>
          </div>
        </div>
      </div>

      {data.notes && (
        <div>
          <h4 className="font-medium mb-1">Note:</h4>
          <p className="text-sm border border-gray-300 p-2 bg-gray-50 rounded">
            {data.notes}
          </p>
        </div>
      )}

      <div className="text-xs text-gray-500">
        <p>
          Thank you for your payment. Please retain this receipt for your
          records.
        </p>
        <p>For billing inquiries, please contact our accounts department.</p>
      </div>
    </div>
  );
};

export default BillReceiptPrint;
