"use client";
import React, { useRef } from "react";
import { useReactToPrint } from "react-to-print";
import RefererPrint from "./RefererPrint";
import PrescriptionPrint from "./PrescriptionPrint";

const PrintHandeler: React.FC<any> = ({
  styleForBtn,
  printOptions,
  PrescriptionAndReferData,
  doctorData,
  patientData,
}: any) => {
  const printRef = useRef(null);
  const handlePrint = useReactToPrint({
    content: () => printRef.current,
    pageStyle: `
        @page { 
          size: A4; 
          margin: 5mm; 
        }
        body {
          -webkit-print-color-adjust: exact;
        }
        .print-container {
          position: relative;
          width: 100%;
          height: 100%;
        }
        .print-footer {
          content: 'This report generated by DardiBook software';
          position: absolute;
          bottom: 10px;
          left: 0;
          width: 100%;
          text-align: center;
          font-size: 10px;
          color: gray;
        }
        .bg-cover {
          position: fixed;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background-image: url('/Logo.svg');
          background-size: 60% 60%;
          opacity: 0.1;
          z-index: -1;
        }
        .page-break {
        page-break-before: always;
      }
      `,
  });

  return (
    <div className="w-full join-item flex flex-col">
      <button onClick={handlePrint} className={styleForBtn}>
        Print Prescription
      </button>
      <div ref={printRef} className="hide-this-compo">
        {printOptions.IsPrescription ? (
          <PrescriptionPrint
            patientInfo={patientData}
            hospitalInfo={doctorData}
            prescriptionInfo={PrescriptionAndReferData}
          />
        ) : (
          <></>
        )}
        {printOptions.IsPrescription && printOptions.IsRefer ? (
          <div className="page-break"></div>
        ) : (
          <></>
        )}
        {printOptions.IsRefer ? (
          <RefererPrint
            patientInfo={patientData}
            hospitalInfo={doctorData}
            refererInfo={PrescriptionAndReferData.refer}
          />
        ) : (
          <></>
        )}
      </div>
    </div>
  );
};

export default PrintHandeler;
